from __future__ import annotations

from sqlalchemy.orm import Session

from models.compliance import ComplianceRule


COMPLIANCE_RULES: list[dict[str, object]] = [
    # periodic reporting (8)
    {
        "category": "reporting",
        "subcategory": "periodic",
        "rule_code": "RPT-M-01",
        "title": "VICS 월간보고 (1308 투자현황)",
        "description": "전월 투자현황을 VICS 1308 코드로 보고",
        "frequency": "monthly",
        "deadline_rule": "M+7d",
        "target_system": "VICS",
        "guideline_ref": "농식품모태 사후관리 가이드라인 제10조",
        "fund_type_filter": "농식품",
    },
    {
        "category": "reporting",
        "subcategory": "periodic",
        "rule_code": "RPT-M-02",
        "title": "VICS 월간보고 (1309 조합현황)",
        "description": "조합 및 LP 변동현황을 VICS 1309 코드로 보고",
        "frequency": "monthly",
        "deadline_rule": "M+7d",
        "target_system": "VICS",
        "guideline_ref": "농식품모태 사후관리 가이드라인 제10조",
        "fund_type_filter": "농식품",
    },
    {
        "category": "reporting",
        "subcategory": "periodic",
        "rule_code": "RPT-M-03",
        "title": "VICS 월간보고 (1329 운용현황)",
        "description": "운용현황 및 NAV 데이터를 VICS 1329 코드로 보고",
        "frequency": "monthly",
        "deadline_rule": "M+7d",
        "target_system": "VICS",
        "guideline_ref": "농식품모태 사후관리 가이드라인 제10조",
        "fund_type_filter": "농식품",
    },
    {
        "category": "reporting",
        "subcategory": "periodic",
        "rule_code": "RPT-M-04",
        "title": "KiiPS 월간보고",
        "description": "KiiPS 월간 투자/운용 데이터 보고",
        "frequency": "monthly",
        "deadline_rule": "M+7d",
        "target_system": "KiiPS",
        "guideline_ref": "한국벤처투자 보고지침",
        "fund_type_filter": "all",
    },
    {
        "category": "reporting",
        "subcategory": "periodic",
        "rule_code": "RPT-Q-01",
        "title": "분기 내부보고회",
        "description": "분기별 내부보고회 개최 및 보고자료 확정",
        "frequency": "quarterly",
        "deadline_rule": "Q+30d",
        "target_system": "내부",
        "guideline_ref": "내부 운용지침 제11조",
        "fund_type_filter": "all",
    },
    {
        "category": "reporting",
        "subcategory": "periodic",
        "rule_code": "RPT-Q-02",
        "title": "분기 서류 7종 수집",
        "description": "피투자사 분기 필수 서류 7종 수집 및 검증",
        "frequency": "quarterly",
        "deadline_rule": "Q+60d",
        "target_system": "내부",
        "guideline_ref": "내부 운용지침 제12조",
        "fund_type_filter": "all",
    },
    {
        "category": "reporting",
        "subcategory": "periodic",
        "rule_code": "RPT-H-01",
        "title": "반기 영업보고서",
        "description": "반기 영업보고서 작성 및 제출",
        "frequency": "semi_annual",
        "deadline_rule": "H+45d",
        "target_system": "농금원",
        "guideline_ref": "농금원 운용지침 제8조",
        "fund_type_filter": "all",
    },
    {
        "category": "reporting",
        "subcategory": "periodic",
        "rule_code": "RPT-A-01",
        "title": "연간 결산보고서",
        "description": "연간 결산보고서 작성 및 제출",
        "frequency": "annual",
        "deadline_rule": "Y+90d",
        "target_system": "농금원",
        "guideline_ref": "농금원 운용지침 제9조",
        "fund_type_filter": "all",
    },
    # adhoc reporting (6)
    {
        "category": "reporting",
        "subcategory": "adhoc",
        "rule_code": "RPT-E-01",
        "title": "투자 실행 수시보고",
        "description": "투자 실행 발생 시 5영업일 이내 수시보고",
        "trigger_event": "investment_created",
        "deadline_rule": "event+5bd",
        "target_system": "VICS",
        "guideline_ref": "농식품모태 가이드라인 제12조",
        "fund_type_filter": "all",
    },
    {
        "category": "reporting",
        "subcategory": "adhoc",
        "rule_code": "RPT-E-02",
        "title": "투자 회수 수시보고",
        "description": "회수/매각 발생 시 5영업일 이내 수시보고",
        "trigger_event": "investment_exited",
        "deadline_rule": "event+5bd",
        "target_system": "VICS",
        "guideline_ref": "농식품모태 가이드라인 제12조",
        "fund_type_filter": "all",
    },
    {
        "category": "reporting",
        "subcategory": "adhoc",
        "rule_code": "RPT-E-03",
        "title": "LP 변경 수시보고",
        "description": "LP 가입/탈퇴/양도 발생 시 10영업일 이내 보고",
        "trigger_event": "lp_changed",
        "deadline_rule": "event+10bd",
        "target_system": "VICS",
        "guideline_ref": "농식품모태 가이드라인 제13조",
        "fund_type_filter": "all",
    },
    {
        "category": "reporting",
        "subcategory": "adhoc",
        "rule_code": "RPT-E-04",
        "title": "규약 변경 수시보고",
        "description": "규약 변경 시 수시보고",
        "trigger_event": "fund_terms_changed",
        "deadline_rule": "event+10bd",
        "target_system": "농금원",
        "guideline_ref": "농금원 운용지침 제14조",
        "fund_type_filter": "all",
    },
    {
        "category": "reporting",
        "subcategory": "adhoc",
        "rule_code": "RPT-E-05",
        "title": "해외투자 수시보고",
        "description": "해외투자 집행 시 수시보고",
        "trigger_event": "overseas_investment",
        "deadline_rule": "event+5bd",
        "target_system": "농금원",
        "guideline_ref": "농금원 운용지침 제15조",
        "fund_type_filter": "all",
    },
    {
        "category": "reporting",
        "subcategory": "adhoc",
        "rule_code": "RPT-E-06",
        "title": "배분 수시보고",
        "description": "LP 배분 실행 시 수시보고",
        "trigger_event": "distribution_executed",
        "deadline_rule": "event+5bd",
        "target_system": "VICS",
        "guideline_ref": "농식품모태 가이드라인 제13조",
        "fund_type_filter": "all",
    },
    # investment limits (5)
    {
        "category": "investment_limit",
        "subcategory": "limit_same_company",
        "rule_code": "LMT-01",
        "title": "동일기업 투자한도 15%",
        "description": "동일기업 누적 투자액은 약정총액의 15% 이내",
        "target_system": "내부",
        "guideline_ref": "농식품모태 가이드라인 제16조",
        "fund_type_filter": "all",
    },
    {
        "category": "investment_limit",
        "subcategory": "limit_overseas",
        "rule_code": "LMT-02",
        "title": "해외투자 한도 20%",
        "description": "해외투자 누적 투자액은 약정총액의 20% 이내",
        "target_system": "내부",
        "guideline_ref": "농식품모태 가이드라인 제17조",
        "fund_type_filter": "all",
    },
    {
        "category": "investment_limit",
        "subcategory": "affiliate_prohibited",
        "rule_code": "LMT-03",
        "title": "GP 계열사 투자 금지",
        "description": "GP 계열사 및 특수관계인 투자 금지",
        "target_system": "내부",
        "guideline_ref": "농식품모태 가이드라인 제18조",
        "fund_type_filter": "all",
    },
    {
        "category": "investment_limit",
        "subcategory": "real_estate_limit",
        "rule_code": "LMT-04",
        "title": "부동산 관련 투자 제한",
        "description": "비허용 부동산 직접 투자 금지",
        "target_system": "내부",
        "guideline_ref": "농식품모태 가이드라인 제19조",
        "fund_type_filter": "all",
    },
    {
        "category": "investment_limit",
        "subcategory": "listed_company_limit",
        "rule_code": "LMT-05",
        "title": "상장기업 투자 제한",
        "description": "상장기업 직접 투자 제한 규정",
        "target_system": "내부",
        "guideline_ref": "농식품모태 가이드라인 제20조",
        "fund_type_filter": "all",
    },
    # impairment (4)
    {
        "category": "impairment",
        "subcategory": "capital_impairment",
        "rule_code": "IMP-01",
        "title": "자본잠식 50% 이상",
        "description": "납입자본금 대비 자본잠식률 50% 이상 시 손상검토",
        "target_system": "내부",
        "guideline_ref": "자산건전성 기준 제4조",
        "fund_type_filter": "all",
    },
    {
        "category": "impairment",
        "subcategory": "loss_streak",
        "rule_code": "IMP-02",
        "title": "3기 연속 당기순손실",
        "description": "최근 3개 분기 연속 순손실 발생 시 손상검토",
        "target_system": "내부",
        "guideline_ref": "자산건전성 기준 제5조",
        "fund_type_filter": "all",
    },
    {
        "category": "impairment",
        "subcategory": "revenue_decline",
        "rule_code": "IMP-03",
        "title": "2기 연속 매출 감소",
        "description": "최근 2개 분기 연속 매출 감소 시 부분 손상검토",
        "target_system": "내부",
        "guideline_ref": "자산건전성 기준 제6조",
        "fund_type_filter": "all",
    },
    {
        "category": "impairment",
        "subcategory": "fair_value_decline",
        "rule_code": "IMP-04",
        "title": "공정가치 급락",
        "description": "공정가치가 유의미하게 하락한 경우 손상검토",
        "target_system": "내부",
        "guideline_ref": "자산건전성 기준 제7조",
        "fund_type_filter": "all",
    },
    # asset rating (5)
    {
        "category": "asset_rating",
        "subcategory": "rating",
        "rule_code": "RAT-AA",
        "title": "자산건전성 등급 AA (정상)",
        "description": "재무/사업 현황 양호",
        "target_system": "내부",
        "guideline_ref": "자산건전성 기준표",
        "fund_type_filter": "all",
    },
    {
        "category": "asset_rating",
        "subcategory": "rating",
        "rule_code": "RAT-A",
        "title": "자산건전성 등급 A (주의)",
        "description": "일부 재무/사업 리스크 존재",
        "target_system": "내부",
        "guideline_ref": "자산건전성 기준표",
        "fund_type_filter": "all",
    },
    {
        "category": "asset_rating",
        "subcategory": "rating",
        "rule_code": "RAT-B",
        "title": "자산건전성 등급 B (요주의)",
        "description": "손상 징후 확인 필요",
        "target_system": "내부",
        "guideline_ref": "자산건전성 기준표",
        "fund_type_filter": "all",
    },
    {
        "category": "asset_rating",
        "subcategory": "rating",
        "rule_code": "RAT-C",
        "title": "자산건전성 등급 C (부실우려)",
        "description": "회수 전략 재검토 필요",
        "target_system": "내부",
        "guideline_ref": "자산건전성 기준표",
        "fund_type_filter": "all",
    },
    {
        "category": "asset_rating",
        "subcategory": "rating",
        "rule_code": "RAT-D",
        "title": "자산건전성 등급 D (부실)",
        "description": "전액손상 또는 회수불능 우려",
        "target_system": "내부",
        "guideline_ref": "자산건전성 기준표",
        "fund_type_filter": "all",
    },
]


def seed_compliance_rules(db: Session) -> tuple[int, int]:
    seeded = 0
    skipped = 0
    for rule_data in COMPLIANCE_RULES:
        existing = db.query(ComplianceRule).filter(ComplianceRule.rule_code == rule_data["rule_code"]).first()
        if existing:
            skipped += 1
            continue
        db.add(ComplianceRule(**rule_data))
        seeded += 1
    db.commit()
    return seeded, skipped
